name: Deploy Saeed Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler@3

      - name: Show Wrangler Version
        run: wrangler --version

      - name: Inject KV/D1 IDs into wrangler.toml
        env:
          CF_KV_ID: ${{ secrets.CF_KV_ID }}
          CF_D1_ID: ${{ secrets.CF_D1_ID }}
        run: |
          sed -i "s/replace-with-your-kv-id/${CF_KV_ID}/g" wrangler.toml
          sed -i "s/replace-with-your-d1-id/${CF_D1_ID}/g" wrangler.toml

      - name: Initialize Worker project
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy --dry-run || true

      - name: Set Cloudflare Worker secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SETUP_TOKEN: ${{ secrets.SETUP_TOKEN }}
          TELEGRAM_WEBHOOK_SECRET: ${{ secrets.TELEGRAM_WEBHOOK_SECRET }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -n "$TELEGRAM_BOT_TOKEN" ]; then echo -n "$TELEGRAM_BOT_TOKEN" | wrangler secret put TELEGRAM_BOT_TOKEN --name saeed-bot --yes; fi
          if [ -n "$SETUP_TOKEN" ]; then echo -n "$SETUP_TOKEN" | wrangler secret put SETUP_TOKEN --name saeed-bot --yes; fi
          if [ -n "$TELEGRAM_WEBHOOK_SECRET" ]; then echo -n "$TELEGRAM_WEBHOOK_SECRET" | wrangler secret put TELEGRAM_WEBHOOK_SECRET --name saeed-bot --yes; fi
          if [ -n "$HUGGINGFACE_API_KEY" ]; then echo -n "$HUGGINGFACE_API_KEY" | wrangler secret put HUGGINGFACE_API_KEY --name saeed-bot --yes; fi
          if [ -n "$OPENAI_API_KEY" ]; then echo -n "$OPENAI_API_KEY" | wrangler secret put OPENAI_API_KEY --name saeed-bot --yes; fi

      - name: Apply D1 schema (safe)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler d1 execute saeed-db --file=./schema.sql || true

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy
