name: Deploy Saeed Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # اختیاری: اگر wrangler لازم داری (اکشن خودش هم داره، ولی این نسخه standard و شفافه)
      - name: Install Wrangler
        run: npm i -g wrangler@3

      # 1) Secrets رو از GitHub → Workers Project ست می‌کنیم (اولین بار/هر بار اوکیه)
      - name: Set Cloudflare Worker secrets
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SETUP_TOKEN: ${{ secrets.SETUP_TOKEN }}
          TELEGRAM_WEBHOOK_SECRET: ${{ secrets.TELEGRAM_WEBHOOK_SECRET }}
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # احراز هویت با توکن
          export CLOUDFLARE_API_TOKEN="$CF_API_TOKEN"

          # پروژه باید طبق wrangler.toml هم‌نام باشه (name = "saeed-bot")
          # اگر اولین باره، wrangler خودش پروژه رو می‌سازه موقع deploy.

          # این‌ها فقط اگر مقدار داشته باشن ست می‌شن
          if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
            echo -n "$TELEGRAM_BOT_TOKEN" | wrangler secret put TELEGRAM_BOT_TOKEN --yes
          fi
          if [ -n "$SETUP_TOKEN" ]; then
            echo -n "$SETUP_TOKEN" | wrangler secret put SETUP_TOKEN --yes
          fi
          if [ -n "$TELEGRAM_WEBHOOK_SECRET" ]; then
            echo -n "$TELEGRAM_WEBHOOK_SECRET" | wrangler secret put TELEGRAM_WEBHOOK_SECRET --yes
          fi
          if [ -n "$HUGGINGFACE_API_KEY" ]; then
            echo -n "$HUGGINGFACE_API_KEY" | wrangler secret put HUGGINGFACE_API_KEY --yes
          fi
          if [ -n "$OPENAI_API_KEY" ]; then
            echo -n "$OPENAI_API_KEY" | wrangler secret put OPENAI_API_KEY --yes
          fi

      # 2) اجرای اسکیما D1 (اگر قبلاً ساختی/اجرا کردی، این مرحله harmless است)
      - name: Apply D1 schema
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler d1 execute saeed-db --file=./schema.sql || true

      # 3) دیپلوی
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          wrangler deploy
